export CUDA_VISIBLE_DEVICES=0  
python main.py \
--device cuda:1 \
--seed 1 \
--drop_out \
--early_stopping \
--lr 1e-4 \
--k 10 \
--label_frac 1 \
--bag_loss ce \
--task 'task_tcga_brca_subtyping' \
--results_dir 'results' \
--exp_code 'tcga_brca_lh' \
--model_type Text_retrevial \
--mode transformer \
--log_data \
--data_root_dir '/data/shihuazhan/conch_features/brca' \
--data_folder_s 'pt_files' \
--data_folder_l 'pt_files' \
--split_dir 'tcga_brca/seed=1/splits10/4shots_10folds' \
--text_prompt_path 'text_prompt/TCGA_Brca_two_scale_text_prompt.csv' \
--prototype_number 16 \
--csv_path '/data3/Public/TCGA_BRCA/slide_name_file.csv' \
--clip_model_type conch \
--top_k_text_num 20 \
--num_experts 8 \
--num_selected 1 \
--topk_ratio 0.2 \